### ISSUE TITLE
Mise a jour de mardi 

### ISSUE THREAD

**Issue by Yassine3isi** [viclew1/VLDofusBotSniffer#6]
Salut bg encore une fois , 
Peux - tu partager comment tu push l'update des messages id du protocol updater vers ce sniffer
tant que je joue dofus pour le moment , je peux faire des pull requests de l'update de mardi si le process est simple
merci bg

**Comment by viclew1** [comment]
Hello,

C'est good pour aujourd'hui ! 
C'est cool de ta part si tu fais des PR pour ça, si tu veux le faire à la mano, il y a une explication ici : https://github.com/viclew1/VLDofusBot/issues/25

En attendant qu'un jour je fasse un truc automatisé (même si ça me soule un peu de rajouter du code pour gérer flash sachant qu'il y aura surement le passage à unity bientôt)

Bonne soirée

**Comment by Yassine3isi** [comment]
Merci Beaucoup!
Pour info : la Dofus unity c'est encore loin d'être réalisé, Surtout que le bêta d'unity a été retarder pour fin 2024.

**Comment by viclew1** [comment]
Ah ouais, très bien mdr, je sais pas ce qui m'a pris de m'attendre à des délais à peu près respectés
